hide extension failed msg for cov test

diff --git a/ci/local/share/flags/ext/cpu b/ci/local/share/flags/ext/cpu
--- a/ci/local/share/flags/ext/cpu
+++ b/ci/local/share/flags/ext/cpu
@@ -1,3 +1,3 @@
 #!/usr/bin/env bash
 echo "cpu test"
-echo "test error" 1>&2 && false
+# echo "test error" 1>&2 && false
